name: Build Docker Image for Flask Backend App

on:
  push:
    branches:
      - main
      - facetracker-docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build all 3 images

    - name: Build and Push Flask Backend
      id: docker_build_fbe
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./be-flask/build/Dockerfile
        push: true
        tags: nickage2023/psu-cv-fbe:latest

    - name: Build and Push React Frontend
      id: docker_build_rfe
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./front-end/Dockerfile
        push: true
        tags: nickage2023/psu-cv-rfe:latest

    - name: Build and Push Facetracker
      id: docker_build_ftr
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./facetracker/Dockerfile
        push: true
        tags: nickage2023/psu-cv-ftr:latest

    # Deploy all 3 images to AWS EC2

    - name: SSH into AWS EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USERNAME }}
        key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
        script: |
          sudo docker stop psu-cv-ftr || true
          sudo docker stop psu-cv-fbe || true
          sudo docker stop psu-cv-rfe || true
          sudo docker rm -f psu-cv-ftr || true
          sudo docker rm -f psu-cv-fbe || true
          sudo docker rm -f psu-cv-rfe || true
          sudo docker rmi -f psu-cv-ftr:latest || true
          sudo docker rmi -f psu-cv-fbe:latest || true
          sudo docker rmi -f psu-cv-rfe:latest || true
          sudo docker pull nickage2023/psu-cv-rfe:latest
          sudo docker pull nickage2023/psu-cv-fbe:latest
          sudo docker pull nickage2023/psu-cv-ftr:latest
          sudo docker run -d --name psu-cv-rfe -p 80:3000 nickage2023/psu-cv-rfe:latest
          sudo docker run -d --name psu-cv-fbe -p 5000:5000 nickage2023/psu-cv-fbe:latest
          sudo docker run -d --name psu-cv-ftr \
                        -e RTSP_SERVER_ADDRESS="${{ secrets.CV_WEBCAM_HOST }}" \
                        -e RTSP_PASSWORD="${{ secrets.CV_WEBCAM_PASSWORD }}" \
                        -e RTSP_USERNAME="${{ secrets.CV_WEBCAM_USER }}" \
                        nickage2023/psu-cv-ftr:latest
