name: Build Docker Image for Flask Backend App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

   # - name: Test CLI Run
   #   with:
   #     context: be-flask
   #   run: pwd
    - name: Set working directory
      run: cd ./be-flask/build/ 

    - name: LS 
      run: ls -ls 
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./be-flask/build/Dockerfile
        push: true
        tags: nickage2023/psu-comp-vision:latest


